--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY adder1b IS
PORT(
  a	: IN STD_LOGIC;
  b	: IN STD_LOGIC;
  cin	: IN STD_LOGIC;
  s	: OUT STD_LOGIC;
  cout	: OUT STD_LOGIC
);
END adder1b;

ARCHITECTURE RTL OF adder1b IS
BEGIN
  cout <= ((a AND b) OR (cin AND (a XOR b)));
  s <= ((a XOR b) XOR cin);
END RTL;
